Fix duplicate TypedQuery in classpath
java.lang.NoSuchMethodError: `java.util.stream.Stream
javax.persistence.TypedQuery.getResultStream()` sometimes happens
because of duplicate TypedQuery in classpath.

Besides, `hibernate-jpa-api` is deprecated, and
`javax.persistence:javax.persistence-api:2.2` should be used instead.

Signed-off-by: Pierre Belloy <p.belloy@axelor.com>